-- 001-init.sql

CREATE TABLE book
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    author VARCHAR(255)                            NOT NULL,
    year   INTEGER                                 NOT NULL,
    read   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);